// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: apply/v1/apply.proto

package applyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplyService_CreateApplication_FullMethodName           = "/hirehub.apply.v1.ApplyService/CreateApplication"
	ApplyService_GetApplication_FullMethodName              = "/hirehub.apply.v1.ApplyService/GetApplication"
	ApplyService_UpdateApplication_FullMethodName           = "/hirehub.apply.v1.ApplyService/UpdateApplication"
	ApplyService_DeleteApplication_FullMethodName           = "/hirehub.apply.v1.ApplyService/DeleteApplication"
	ApplyService_ListApplications_FullMethodName            = "/hirehub.apply.v1.ApplyService/ListApplications"
	ApplyService_GetApplicationsByJob_FullMethodName        = "/hirehub.apply.v1.ApplyService/GetApplicationsByJob"
	ApplyService_GetApplicationsByUser_FullMethodName       = "/hirehub.apply.v1.ApplyService/GetApplicationsByUser"
	ApplyService_CheckDuplicateApplication_FullMethodName   = "/hirehub.apply.v1.ApplyService/CheckDuplicateApplication"
	ApplyService_WithdrawApplication_FullMethodName         = "/hirehub.apply.v1.ApplyService/WithdrawApplication"
	ApplyService_UpdateApplicationStatus_FullMethodName     = "/hirehub.apply.v1.ApplyService/UpdateApplicationStatus"
	ApplyService_BulkUpdateApplicationStatus_FullMethodName = "/hirehub.apply.v1.ApplyService/BulkUpdateApplicationStatus"
	ApplyService_CreateApplicationEvent_FullMethodName      = "/hirehub.apply.v1.ApplyService/CreateApplicationEvent"
	ApplyService_ListApplicationEvents_FullMethodName       = "/hirehub.apply.v1.ApplyService/ListApplicationEvents"
	ApplyService_CreateInterview_FullMethodName             = "/hirehub.apply.v1.ApplyService/CreateInterview"
	ApplyService_GetInterview_FullMethodName                = "/hirehub.apply.v1.ApplyService/GetInterview"
	ApplyService_UpdateInterview_FullMethodName             = "/hirehub.apply.v1.ApplyService/UpdateInterview"
	ApplyService_DeleteInterview_FullMethodName             = "/hirehub.apply.v1.ApplyService/DeleteInterview"
	ApplyService_ListInterviews_FullMethodName              = "/hirehub.apply.v1.ApplyService/ListInterviews"
	ApplyService_GetInterviewsByApplication_FullMethodName  = "/hirehub.apply.v1.ApplyService/GetInterviewsByApplication"
	ApplyService_RescheduleInterview_FullMethodName         = "/hirehub.apply.v1.ApplyService/RescheduleInterview"
	ApplyService_CancelInterview_FullMethodName             = "/hirehub.apply.v1.ApplyService/CancelInterview"
	ApplyService_CompleteInterview_FullMethodName           = "/hirehub.apply.v1.ApplyService/CompleteInterview"
	ApplyService_GetApplicationStats_FullMethodName         = "/hirehub.apply.v1.ApplyService/GetApplicationStats"
)

// ApplyServiceClient is the client API for ApplyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplyServiceClient interface {
	// Application CRUD
	CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error)
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*GetApplicationResponse, error)
	UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error)
	DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error)
	GetApplicationsByJob(ctx context.Context, in *GetApplicationsByJobRequest, opts ...grpc.CallOption) (*GetApplicationsByJobResponse, error)
	GetApplicationsByUser(ctx context.Context, in *GetApplicationsByUserRequest, opts ...grpc.CallOption) (*GetApplicationsByUserResponse, error)
	// Application actions
	CheckDuplicateApplication(ctx context.Context, in *CheckDuplicateApplicationRequest, opts ...grpc.CallOption) (*CheckDuplicateApplicationResponse, error)
	WithdrawApplication(ctx context.Context, in *WithdrawApplicationRequest, opts ...grpc.CallOption) (*WithdrawApplicationResponse, error)
	UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...grpc.CallOption) (*UpdateApplicationStatusResponse, error)
	BulkUpdateApplicationStatus(ctx context.Context, in *BulkUpdateApplicationStatusRequest, opts ...grpc.CallOption) (*BulkUpdateApplicationStatusResponse, error)
	// Application events
	CreateApplicationEvent(ctx context.Context, in *CreateApplicationEventRequest, opts ...grpc.CallOption) (*CreateApplicationEventResponse, error)
	ListApplicationEvents(ctx context.Context, in *ListApplicationEventsRequest, opts ...grpc.CallOption) (*ListApplicationEventsResponse, error)
	// Interview CRUD
	CreateInterview(ctx context.Context, in *CreateInterviewRequest, opts ...grpc.CallOption) (*CreateInterviewResponse, error)
	GetInterview(ctx context.Context, in *GetInterviewRequest, opts ...grpc.CallOption) (*GetInterviewResponse, error)
	UpdateInterview(ctx context.Context, in *UpdateInterviewRequest, opts ...grpc.CallOption) (*UpdateInterviewResponse, error)
	DeleteInterview(ctx context.Context, in *DeleteInterviewRequest, opts ...grpc.CallOption) (*DeleteInterviewResponse, error)
	ListInterviews(ctx context.Context, in *ListInterviewsRequest, opts ...grpc.CallOption) (*ListInterviewsResponse, error)
	GetInterviewsByApplication(ctx context.Context, in *GetInterviewsByApplicationRequest, opts ...grpc.CallOption) (*GetInterviewsByApplicationResponse, error)
	// Interview actions
	RescheduleInterview(ctx context.Context, in *RescheduleInterviewRequest, opts ...grpc.CallOption) (*RescheduleInterviewResponse, error)
	CancelInterview(ctx context.Context, in *CancelInterviewRequest, opts ...grpc.CallOption) (*CancelInterviewResponse, error)
	CompleteInterview(ctx context.Context, in *CompleteInterviewRequest, opts ...grpc.CallOption) (*CompleteInterviewResponse, error)
	// Statistics
	GetApplicationStats(ctx context.Context, in *GetApplicationStatsRequest, opts ...grpc.CallOption) (*GetApplicationStatsResponse, error)
}

type applyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplyServiceClient(cc grpc.ClientConnInterface) ApplyServiceClient {
	return &applyServiceClient{cc}
}

func (c *applyServiceClient) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_CreateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*GetApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_GetApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_UpdateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_DeleteApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplyService_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) GetApplicationsByJob(ctx context.Context, in *GetApplicationsByJobRequest, opts ...grpc.CallOption) (*GetApplicationsByJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationsByJobResponse)
	err := c.cc.Invoke(ctx, ApplyService_GetApplicationsByJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) GetApplicationsByUser(ctx context.Context, in *GetApplicationsByUserRequest, opts ...grpc.CallOption) (*GetApplicationsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationsByUserResponse)
	err := c.cc.Invoke(ctx, ApplyService_GetApplicationsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) CheckDuplicateApplication(ctx context.Context, in *CheckDuplicateApplicationRequest, opts ...grpc.CallOption) (*CheckDuplicateApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDuplicateApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_CheckDuplicateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) WithdrawApplication(ctx context.Context, in *WithdrawApplicationRequest, opts ...grpc.CallOption) (*WithdrawApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_WithdrawApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...grpc.CallOption) (*UpdateApplicationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApplicationStatusResponse)
	err := c.cc.Invoke(ctx, ApplyService_UpdateApplicationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) BulkUpdateApplicationStatus(ctx context.Context, in *BulkUpdateApplicationStatusRequest, opts ...grpc.CallOption) (*BulkUpdateApplicationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUpdateApplicationStatusResponse)
	err := c.cc.Invoke(ctx, ApplyService_BulkUpdateApplicationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) CreateApplicationEvent(ctx context.Context, in *CreateApplicationEventRequest, opts ...grpc.CallOption) (*CreateApplicationEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApplicationEventResponse)
	err := c.cc.Invoke(ctx, ApplyService_CreateApplicationEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) ListApplicationEvents(ctx context.Context, in *ListApplicationEventsRequest, opts ...grpc.CallOption) (*ListApplicationEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationEventsResponse)
	err := c.cc.Invoke(ctx, ApplyService_ListApplicationEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) CreateInterview(ctx context.Context, in *CreateInterviewRequest, opts ...grpc.CallOption) (*CreateInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_CreateInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) GetInterview(ctx context.Context, in *GetInterviewRequest, opts ...grpc.CallOption) (*GetInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_GetInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) UpdateInterview(ctx context.Context, in *UpdateInterviewRequest, opts ...grpc.CallOption) (*UpdateInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_UpdateInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) DeleteInterview(ctx context.Context, in *DeleteInterviewRequest, opts ...grpc.CallOption) (*DeleteInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_DeleteInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) ListInterviews(ctx context.Context, in *ListInterviewsRequest, opts ...grpc.CallOption) (*ListInterviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterviewsResponse)
	err := c.cc.Invoke(ctx, ApplyService_ListInterviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) GetInterviewsByApplication(ctx context.Context, in *GetInterviewsByApplicationRequest, opts ...grpc.CallOption) (*GetInterviewsByApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterviewsByApplicationResponse)
	err := c.cc.Invoke(ctx, ApplyService_GetInterviewsByApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) RescheduleInterview(ctx context.Context, in *RescheduleInterviewRequest, opts ...grpc.CallOption) (*RescheduleInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduleInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_RescheduleInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) CancelInterview(ctx context.Context, in *CancelInterviewRequest, opts ...grpc.CallOption) (*CancelInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_CancelInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) CompleteInterview(ctx context.Context, in *CompleteInterviewRequest, opts ...grpc.CallOption) (*CompleteInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteInterviewResponse)
	err := c.cc.Invoke(ctx, ApplyService_CompleteInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyServiceClient) GetApplicationStats(ctx context.Context, in *GetApplicationStatsRequest, opts ...grpc.CallOption) (*GetApplicationStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationStatsResponse)
	err := c.cc.Invoke(ctx, ApplyService_GetApplicationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplyServiceServer is the server API for ApplyService service.
// All implementations must embed UnimplementedApplyServiceServer
// for forward compatibility.
type ApplyServiceServer interface {
	// Application CRUD
	CreateApplication(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error)
	GetApplication(context.Context, *GetApplicationRequest) (*GetApplicationResponse, error)
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*UpdateApplicationResponse, error)
	DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	GetApplicationsByJob(context.Context, *GetApplicationsByJobRequest) (*GetApplicationsByJobResponse, error)
	GetApplicationsByUser(context.Context, *GetApplicationsByUserRequest) (*GetApplicationsByUserResponse, error)
	// Application actions
	CheckDuplicateApplication(context.Context, *CheckDuplicateApplicationRequest) (*CheckDuplicateApplicationResponse, error)
	WithdrawApplication(context.Context, *WithdrawApplicationRequest) (*WithdrawApplicationResponse, error)
	UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*UpdateApplicationStatusResponse, error)
	BulkUpdateApplicationStatus(context.Context, *BulkUpdateApplicationStatusRequest) (*BulkUpdateApplicationStatusResponse, error)
	// Application events
	CreateApplicationEvent(context.Context, *CreateApplicationEventRequest) (*CreateApplicationEventResponse, error)
	ListApplicationEvents(context.Context, *ListApplicationEventsRequest) (*ListApplicationEventsResponse, error)
	// Interview CRUD
	CreateInterview(context.Context, *CreateInterviewRequest) (*CreateInterviewResponse, error)
	GetInterview(context.Context, *GetInterviewRequest) (*GetInterviewResponse, error)
	UpdateInterview(context.Context, *UpdateInterviewRequest) (*UpdateInterviewResponse, error)
	DeleteInterview(context.Context, *DeleteInterviewRequest) (*DeleteInterviewResponse, error)
	ListInterviews(context.Context, *ListInterviewsRequest) (*ListInterviewsResponse, error)
	GetInterviewsByApplication(context.Context, *GetInterviewsByApplicationRequest) (*GetInterviewsByApplicationResponse, error)
	// Interview actions
	RescheduleInterview(context.Context, *RescheduleInterviewRequest) (*RescheduleInterviewResponse, error)
	CancelInterview(context.Context, *CancelInterviewRequest) (*CancelInterviewResponse, error)
	CompleteInterview(context.Context, *CompleteInterviewRequest) (*CompleteInterviewResponse, error)
	// Statistics
	GetApplicationStats(context.Context, *GetApplicationStatsRequest) (*GetApplicationStatsResponse, error)
	mustEmbedUnimplementedApplyServiceServer()
}

// UnimplementedApplyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplyServiceServer struct{}

func (UnimplementedApplyServiceServer) CreateApplication(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApplication not implemented")
}
func (UnimplementedApplyServiceServer) GetApplication(context.Context, *GetApplicationRequest) (*GetApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplication not implemented")
}
func (UnimplementedApplyServiceServer) UpdateApplication(context.Context, *UpdateApplicationRequest) (*UpdateApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApplication not implemented")
}
func (UnimplementedApplyServiceServer) DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (UnimplementedApplyServiceServer) ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedApplyServiceServer) GetApplicationsByJob(context.Context, *GetApplicationsByJobRequest) (*GetApplicationsByJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationsByJob not implemented")
}
func (UnimplementedApplyServiceServer) GetApplicationsByUser(context.Context, *GetApplicationsByUserRequest) (*GetApplicationsByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationsByUser not implemented")
}
func (UnimplementedApplyServiceServer) CheckDuplicateApplication(context.Context, *CheckDuplicateApplicationRequest) (*CheckDuplicateApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDuplicateApplication not implemented")
}
func (UnimplementedApplyServiceServer) WithdrawApplication(context.Context, *WithdrawApplicationRequest) (*WithdrawApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawApplication not implemented")
}
func (UnimplementedApplyServiceServer) UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*UpdateApplicationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApplicationStatus not implemented")
}
func (UnimplementedApplyServiceServer) BulkUpdateApplicationStatus(context.Context, *BulkUpdateApplicationStatusRequest) (*BulkUpdateApplicationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkUpdateApplicationStatus not implemented")
}
func (UnimplementedApplyServiceServer) CreateApplicationEvent(context.Context, *CreateApplicationEventRequest) (*CreateApplicationEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApplicationEvent not implemented")
}
func (UnimplementedApplyServiceServer) ListApplicationEvents(context.Context, *ListApplicationEventsRequest) (*ListApplicationEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicationEvents not implemented")
}
func (UnimplementedApplyServiceServer) CreateInterview(context.Context, *CreateInterviewRequest) (*CreateInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInterview not implemented")
}
func (UnimplementedApplyServiceServer) GetInterview(context.Context, *GetInterviewRequest) (*GetInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterview not implemented")
}
func (UnimplementedApplyServiceServer) UpdateInterview(context.Context, *UpdateInterviewRequest) (*UpdateInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInterview not implemented")
}
func (UnimplementedApplyServiceServer) DeleteInterview(context.Context, *DeleteInterviewRequest) (*DeleteInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInterview not implemented")
}
func (UnimplementedApplyServiceServer) ListInterviews(context.Context, *ListInterviewsRequest) (*ListInterviewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterviews not implemented")
}
func (UnimplementedApplyServiceServer) GetInterviewsByApplication(context.Context, *GetInterviewsByApplicationRequest) (*GetInterviewsByApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterviewsByApplication not implemented")
}
func (UnimplementedApplyServiceServer) RescheduleInterview(context.Context, *RescheduleInterviewRequest) (*RescheduleInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RescheduleInterview not implemented")
}
func (UnimplementedApplyServiceServer) CancelInterview(context.Context, *CancelInterviewRequest) (*CancelInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInterview not implemented")
}
func (UnimplementedApplyServiceServer) CompleteInterview(context.Context, *CompleteInterviewRequest) (*CompleteInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteInterview not implemented")
}
func (UnimplementedApplyServiceServer) GetApplicationStats(context.Context, *GetApplicationStatsRequest) (*GetApplicationStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationStats not implemented")
}
func (UnimplementedApplyServiceServer) mustEmbedUnimplementedApplyServiceServer() {}
func (UnimplementedApplyServiceServer) testEmbeddedByValue()                      {}

// UnsafeApplyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplyServiceServer will
// result in compilation errors.
type UnsafeApplyServiceServer interface {
	mustEmbedUnimplementedApplyServiceServer()
}

func RegisterApplyServiceServer(s grpc.ServiceRegistrar, srv ApplyServiceServer) {
	// If the following call panics, it indicates UnimplementedApplyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplyService_ServiceDesc, srv)
}

func _ApplyService_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_CreateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).CreateApplication(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_GetApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_UpdateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).UpdateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_UpdateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).UpdateApplication(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_DeleteApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).DeleteApplication(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_GetApplicationsByJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationsByJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).GetApplicationsByJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_GetApplicationsByJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).GetApplicationsByJob(ctx, req.(*GetApplicationsByJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_GetApplicationsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).GetApplicationsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_GetApplicationsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).GetApplicationsByUser(ctx, req.(*GetApplicationsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_CheckDuplicateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDuplicateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).CheckDuplicateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_CheckDuplicateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).CheckDuplicateApplication(ctx, req.(*CheckDuplicateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_WithdrawApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).WithdrawApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_WithdrawApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).WithdrawApplication(ctx, req.(*WithdrawApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_UpdateApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).UpdateApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_UpdateApplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).UpdateApplicationStatus(ctx, req.(*UpdateApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_BulkUpdateApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpdateApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).BulkUpdateApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_BulkUpdateApplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).BulkUpdateApplicationStatus(ctx, req.(*BulkUpdateApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_CreateApplicationEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).CreateApplicationEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_CreateApplicationEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).CreateApplicationEvent(ctx, req.(*CreateApplicationEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_ListApplicationEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).ListApplicationEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_ListApplicationEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).ListApplicationEvents(ctx, req.(*ListApplicationEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_CreateInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).CreateInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_CreateInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).CreateInterview(ctx, req.(*CreateInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_GetInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).GetInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_GetInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).GetInterview(ctx, req.(*GetInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_UpdateInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).UpdateInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_UpdateInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).UpdateInterview(ctx, req.(*UpdateInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_DeleteInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).DeleteInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_DeleteInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).DeleteInterview(ctx, req.(*DeleteInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_ListInterviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).ListInterviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_ListInterviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).ListInterviews(ctx, req.(*ListInterviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_GetInterviewsByApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterviewsByApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).GetInterviewsByApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_GetInterviewsByApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).GetInterviewsByApplication(ctx, req.(*GetInterviewsByApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_RescheduleInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescheduleInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).RescheduleInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_RescheduleInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).RescheduleInterview(ctx, req.(*RescheduleInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_CancelInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).CancelInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_CancelInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).CancelInterview(ctx, req.(*CancelInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_CompleteInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).CompleteInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_CompleteInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).CompleteInterview(ctx, req.(*CompleteInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyService_GetApplicationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyServiceServer).GetApplicationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyService_GetApplicationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyServiceServer).GetApplicationStats(ctx, req.(*GetApplicationStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplyService_ServiceDesc is the grpc.ServiceDesc for ApplyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hirehub.apply.v1.ApplyService",
	HandlerType: (*ApplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApplication",
			Handler:    _ApplyService_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _ApplyService_GetApplication_Handler,
		},
		{
			MethodName: "UpdateApplication",
			Handler:    _ApplyService_UpdateApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _ApplyService_DeleteApplication_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _ApplyService_ListApplications_Handler,
		},
		{
			MethodName: "GetApplicationsByJob",
			Handler:    _ApplyService_GetApplicationsByJob_Handler,
		},
		{
			MethodName: "GetApplicationsByUser",
			Handler:    _ApplyService_GetApplicationsByUser_Handler,
		},
		{
			MethodName: "CheckDuplicateApplication",
			Handler:    _ApplyService_CheckDuplicateApplication_Handler,
		},
		{
			MethodName: "WithdrawApplication",
			Handler:    _ApplyService_WithdrawApplication_Handler,
		},
		{
			MethodName: "UpdateApplicationStatus",
			Handler:    _ApplyService_UpdateApplicationStatus_Handler,
		},
		{
			MethodName: "BulkUpdateApplicationStatus",
			Handler:    _ApplyService_BulkUpdateApplicationStatus_Handler,
		},
		{
			MethodName: "CreateApplicationEvent",
			Handler:    _ApplyService_CreateApplicationEvent_Handler,
		},
		{
			MethodName: "ListApplicationEvents",
			Handler:    _ApplyService_ListApplicationEvents_Handler,
		},
		{
			MethodName: "CreateInterview",
			Handler:    _ApplyService_CreateInterview_Handler,
		},
		{
			MethodName: "GetInterview",
			Handler:    _ApplyService_GetInterview_Handler,
		},
		{
			MethodName: "UpdateInterview",
			Handler:    _ApplyService_UpdateInterview_Handler,
		},
		{
			MethodName: "DeleteInterview",
			Handler:    _ApplyService_DeleteInterview_Handler,
		},
		{
			MethodName: "ListInterviews",
			Handler:    _ApplyService_ListInterviews_Handler,
		},
		{
			MethodName: "GetInterviewsByApplication",
			Handler:    _ApplyService_GetInterviewsByApplication_Handler,
		},
		{
			MethodName: "RescheduleInterview",
			Handler:    _ApplyService_RescheduleInterview_Handler,
		},
		{
			MethodName: "CancelInterview",
			Handler:    _ApplyService_CancelInterview_Handler,
		},
		{
			MethodName: "CompleteInterview",
			Handler:    _ApplyService_CompleteInterview_Handler,
		},
		{
			MethodName: "GetApplicationStats",
			Handler:    _ApplyService_GetApplicationStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apply/v1/apply.proto",
}
