# Kong CORS Plugin
# Global CORS configuration allowing all origins for demo purposes
# For production, restrict origins to specific domains
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-cors
  labels:
    global: "true"
    app.kubernetes.io/name: kong
    app.kubernetes.io/part-of: hirehub
    app.kubernetes.io/component: plugin
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/description: "Global CORS plugin - allows all origins for demo"
plugin: cors
config:
  # Allow all origins for demo
  # Production: restrict to specific domains like ["https://hirehub.example.com"]
  origins:
    - "*"
  # Allowed HTTP methods
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
  # Allowed request headers
  headers:
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Authorization
    - Content-Type
    - Origin
    - X-Request-ID
    - X-Requested-With
    - X-Correlation-ID
    - X-Trace-ID
  # Headers exposed to the client
  exposed_headers:
    - X-Request-ID
    - X-Correlation-ID
    - X-RateLimit-Limit-Minute
    - X-RateLimit-Remaining-Minute
  # Preflight cache duration (1 hour)
  max_age: 3600
  # Allow credentials (cookies, authorization headers)
  credentials: true
  # Automatically handle preflight requests
  preflight_continue: false
---
# Restrictive CORS for admin APIs
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: admin-cors
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/part-of: hirehub
    app.kubernetes.io/component: plugin
plugin: cors
config:
  # Admin API should have restricted origins
  origins:
    - "https://admin.hirehub.example.com"
    - "http://localhost:3001"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  headers:
    - Accept
    - Authorization
    - Content-Type
    - X-Request-ID
  exposed_headers:
    - X-Request-ID
  max_age: 600
  credentials: true
