// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: notification/v1/notification.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificationService_CreateNotificationTemplate_FullMethodName     = "/hirehub.notification.v1.NotificationService/CreateNotificationTemplate"
	NotificationService_GetNotificationTemplate_FullMethodName        = "/hirehub.notification.v1.NotificationService/GetNotificationTemplate"
	NotificationService_UpdateNotificationTemplate_FullMethodName     = "/hirehub.notification.v1.NotificationService/UpdateNotificationTemplate"
	NotificationService_DeleteNotificationTemplate_FullMethodName     = "/hirehub.notification.v1.NotificationService/DeleteNotificationTemplate"
	NotificationService_ListNotificationTemplates_FullMethodName      = "/hirehub.notification.v1.NotificationService/ListNotificationTemplates"
	NotificationService_GetTemplateByEvent_FullMethodName             = "/hirehub.notification.v1.NotificationService/GetTemplateByEvent"
	NotificationService_CreateNotification_FullMethodName             = "/hirehub.notification.v1.NotificationService/CreateNotification"
	NotificationService_GetNotification_FullMethodName                = "/hirehub.notification.v1.NotificationService/GetNotification"
	NotificationService_ListNotifications_FullMethodName              = "/hirehub.notification.v1.NotificationService/ListNotifications"
	NotificationService_GetNotificationsByUser_FullMethodName         = "/hirehub.notification.v1.NotificationService/GetNotificationsByUser"
	NotificationService_MarkNotificationRead_FullMethodName           = "/hirehub.notification.v1.NotificationService/MarkNotificationRead"
	NotificationService_MarkAllNotificationsRead_FullMethodName       = "/hirehub.notification.v1.NotificationService/MarkAllNotificationsRead"
	NotificationService_DeleteNotification_FullMethodName             = "/hirehub.notification.v1.NotificationService/DeleteNotification"
	NotificationService_GetUnreadCount_FullMethodName                 = "/hirehub.notification.v1.NotificationService/GetUnreadCount"
	NotificationService_SendNotification_FullMethodName               = "/hirehub.notification.v1.NotificationService/SendNotification"
	NotificationService_SendBulkNotification_FullMethodName           = "/hirehub.notification.v1.NotificationService/SendBulkNotification"
	NotificationService_SendMultiChannelNotification_FullMethodName   = "/hirehub.notification.v1.NotificationService/SendMultiChannelNotification"
	NotificationService_RegisterDeviceToken_FullMethodName            = "/hirehub.notification.v1.NotificationService/RegisterDeviceToken"
	NotificationService_UnregisterDeviceToken_FullMethodName          = "/hirehub.notification.v1.NotificationService/UnregisterDeviceToken"
	NotificationService_GetDeviceTokensByUser_FullMethodName          = "/hirehub.notification.v1.NotificationService/GetDeviceTokensByUser"
	NotificationService_DeactivateDeviceToken_FullMethodName          = "/hirehub.notification.v1.NotificationService/DeactivateDeviceToken"
	NotificationService_GetUserNotificationSettings_FullMethodName    = "/hirehub.notification.v1.NotificationService/GetUserNotificationSettings"
	NotificationService_UpdateUserNotificationSettings_FullMethodName = "/hirehub.notification.v1.NotificationService/UpdateUserNotificationSettings"
	NotificationService_CheckNotificationEnabled_FullMethodName       = "/hirehub.notification.v1.NotificationService/CheckNotificationEnabled"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	// Template CRUD
	CreateNotificationTemplate(ctx context.Context, in *CreateNotificationTemplateRequest, opts ...grpc.CallOption) (*CreateNotificationTemplateResponse, error)
	GetNotificationTemplate(ctx context.Context, in *GetNotificationTemplateRequest, opts ...grpc.CallOption) (*GetNotificationTemplateResponse, error)
	UpdateNotificationTemplate(ctx context.Context, in *UpdateNotificationTemplateRequest, opts ...grpc.CallOption) (*UpdateNotificationTemplateResponse, error)
	DeleteNotificationTemplate(ctx context.Context, in *DeleteNotificationTemplateRequest, opts ...grpc.CallOption) (*DeleteNotificationTemplateResponse, error)
	ListNotificationTemplates(ctx context.Context, in *ListNotificationTemplatesRequest, opts ...grpc.CallOption) (*ListNotificationTemplatesResponse, error)
	GetTemplateByEvent(ctx context.Context, in *GetTemplateByEventRequest, opts ...grpc.CallOption) (*GetTemplateByEventResponse, error)
	// Notification CRUD
	CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*CreateNotificationResponse, error)
	GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error)
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	GetNotificationsByUser(ctx context.Context, in *GetNotificationsByUserRequest, opts ...grpc.CallOption) (*GetNotificationsByUserResponse, error)
	MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*MarkNotificationReadResponse, error)
	MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllNotificationsReadResponse, error)
	DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error)
	GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
	// Send notifications
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
	SendBulkNotification(ctx context.Context, in *SendBulkNotificationRequest, opts ...grpc.CallOption) (*SendBulkNotificationResponse, error)
	SendMultiChannelNotification(ctx context.Context, in *SendMultiChannelNotificationRequest, opts ...grpc.CallOption) (*SendMultiChannelNotificationResponse, error)
	// Device tokens
	RegisterDeviceToken(ctx context.Context, in *RegisterDeviceTokenRequest, opts ...grpc.CallOption) (*RegisterDeviceTokenResponse, error)
	UnregisterDeviceToken(ctx context.Context, in *UnregisterDeviceTokenRequest, opts ...grpc.CallOption) (*UnregisterDeviceTokenResponse, error)
	GetDeviceTokensByUser(ctx context.Context, in *GetDeviceTokensByUserRequest, opts ...grpc.CallOption) (*GetDeviceTokensByUserResponse, error)
	DeactivateDeviceToken(ctx context.Context, in *DeactivateDeviceTokenRequest, opts ...grpc.CallOption) (*DeactivateDeviceTokenResponse, error)
	// User settings
	GetUserNotificationSettings(ctx context.Context, in *GetUserNotificationSettingsRequest, opts ...grpc.CallOption) (*GetUserNotificationSettingsResponse, error)
	UpdateUserNotificationSettings(ctx context.Context, in *UpdateUserNotificationSettingsRequest, opts ...grpc.CallOption) (*UpdateUserNotificationSettingsResponse, error)
	CheckNotificationEnabled(ctx context.Context, in *CheckNotificationEnabledRequest, opts ...grpc.CallOption) (*CheckNotificationEnabledResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateNotificationTemplate(ctx context.Context, in *CreateNotificationTemplateRequest, opts ...grpc.CallOption) (*CreateNotificationTemplateResponse, error) {
	out := new(CreateNotificationTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotificationTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotificationTemplate(ctx context.Context, in *GetNotificationTemplateRequest, opts ...grpc.CallOption) (*GetNotificationTemplateResponse, error) {
	out := new(GetNotificationTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotificationTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateNotificationTemplate(ctx context.Context, in *UpdateNotificationTemplateRequest, opts ...grpc.CallOption) (*UpdateNotificationTemplateResponse, error) {
	out := new(UpdateNotificationTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_UpdateNotificationTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteNotificationTemplate(ctx context.Context, in *DeleteNotificationTemplateRequest, opts ...grpc.CallOption) (*DeleteNotificationTemplateResponse, error) {
	out := new(DeleteNotificationTemplateResponse)
	err := c.cc.Invoke(ctx, NotificationService_DeleteNotificationTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListNotificationTemplates(ctx context.Context, in *ListNotificationTemplatesRequest, opts ...grpc.CallOption) (*ListNotificationTemplatesResponse, error) {
	out := new(ListNotificationTemplatesResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotificationTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetTemplateByEvent(ctx context.Context, in *GetTemplateByEventRequest, opts ...grpc.CallOption) (*GetTemplateByEventResponse, error) {
	out := new(GetTemplateByEventResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetTemplateByEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*CreateNotificationResponse, error) {
	out := new(CreateNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error) {
	out := new(GetNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	out := new(ListNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotifications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotificationsByUser(ctx context.Context, in *GetNotificationsByUserRequest, opts ...grpc.CallOption) (*GetNotificationsByUserResponse, error) {
	out := new(GetNotificationsByUserResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotificationsByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*MarkNotificationReadResponse, error) {
	out := new(MarkNotificationReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkNotificationRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllNotificationsReadResponse, error) {
	out := new(MarkAllNotificationsReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkAllNotificationsRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error) {
	out := new(DeleteNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_DeleteNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	out := new(GetUnreadCountResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetUnreadCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendBulkNotification(ctx context.Context, in *SendBulkNotificationRequest, opts ...grpc.CallOption) (*SendBulkNotificationResponse, error) {
	out := new(SendBulkNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendBulkNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendMultiChannelNotification(ctx context.Context, in *SendMultiChannelNotificationRequest, opts ...grpc.CallOption) (*SendMultiChannelNotificationResponse, error) {
	out := new(SendMultiChannelNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendMultiChannelNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) RegisterDeviceToken(ctx context.Context, in *RegisterDeviceTokenRequest, opts ...grpc.CallOption) (*RegisterDeviceTokenResponse, error) {
	out := new(RegisterDeviceTokenResponse)
	err := c.cc.Invoke(ctx, NotificationService_RegisterDeviceToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UnregisterDeviceToken(ctx context.Context, in *UnregisterDeviceTokenRequest, opts ...grpc.CallOption) (*UnregisterDeviceTokenResponse, error) {
	out := new(UnregisterDeviceTokenResponse)
	err := c.cc.Invoke(ctx, NotificationService_UnregisterDeviceToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetDeviceTokensByUser(ctx context.Context, in *GetDeviceTokensByUserRequest, opts ...grpc.CallOption) (*GetDeviceTokensByUserResponse, error) {
	out := new(GetDeviceTokensByUserResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetDeviceTokensByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeactivateDeviceToken(ctx context.Context, in *DeactivateDeviceTokenRequest, opts ...grpc.CallOption) (*DeactivateDeviceTokenResponse, error) {
	out := new(DeactivateDeviceTokenResponse)
	err := c.cc.Invoke(ctx, NotificationService_DeactivateDeviceToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetUserNotificationSettings(ctx context.Context, in *GetUserNotificationSettingsRequest, opts ...grpc.CallOption) (*GetUserNotificationSettingsResponse, error) {
	out := new(GetUserNotificationSettingsResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetUserNotificationSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateUserNotificationSettings(ctx context.Context, in *UpdateUserNotificationSettingsRequest, opts ...grpc.CallOption) (*UpdateUserNotificationSettingsResponse, error) {
	out := new(UpdateUserNotificationSettingsResponse)
	err := c.cc.Invoke(ctx, NotificationService_UpdateUserNotificationSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CheckNotificationEnabled(ctx context.Context, in *CheckNotificationEnabledRequest, opts ...grpc.CallOption) (*CheckNotificationEnabledResponse, error) {
	out := new(CheckNotificationEnabledResponse)
	err := c.cc.Invoke(ctx, NotificationService_CheckNotificationEnabled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	// Template CRUD
	CreateNotificationTemplate(context.Context, *CreateNotificationTemplateRequest) (*CreateNotificationTemplateResponse, error)
	GetNotificationTemplate(context.Context, *GetNotificationTemplateRequest) (*GetNotificationTemplateResponse, error)
	UpdateNotificationTemplate(context.Context, *UpdateNotificationTemplateRequest) (*UpdateNotificationTemplateResponse, error)
	DeleteNotificationTemplate(context.Context, *DeleteNotificationTemplateRequest) (*DeleteNotificationTemplateResponse, error)
	ListNotificationTemplates(context.Context, *ListNotificationTemplatesRequest) (*ListNotificationTemplatesResponse, error)
	GetTemplateByEvent(context.Context, *GetTemplateByEventRequest) (*GetTemplateByEventResponse, error)
	// Notification CRUD
	CreateNotification(context.Context, *CreateNotificationRequest) (*CreateNotificationResponse, error)
	GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error)
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	GetNotificationsByUser(context.Context, *GetNotificationsByUserRequest) (*GetNotificationsByUserResponse, error)
	MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*MarkNotificationReadResponse, error)
	MarkAllNotificationsRead(context.Context, *MarkAllNotificationsReadRequest) (*MarkAllNotificationsReadResponse, error)
	DeleteNotification(context.Context, *DeleteNotificationRequest) (*DeleteNotificationResponse, error)
	GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error)
	// Send notifications
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	SendBulkNotification(context.Context, *SendBulkNotificationRequest) (*SendBulkNotificationResponse, error)
	SendMultiChannelNotification(context.Context, *SendMultiChannelNotificationRequest) (*SendMultiChannelNotificationResponse, error)
	// Device tokens
	RegisterDeviceToken(context.Context, *RegisterDeviceTokenRequest) (*RegisterDeviceTokenResponse, error)
	UnregisterDeviceToken(context.Context, *UnregisterDeviceTokenRequest) (*UnregisterDeviceTokenResponse, error)
	GetDeviceTokensByUser(context.Context, *GetDeviceTokensByUserRequest) (*GetDeviceTokensByUserResponse, error)
	DeactivateDeviceToken(context.Context, *DeactivateDeviceTokenRequest) (*DeactivateDeviceTokenResponse, error)
	// User settings
	GetUserNotificationSettings(context.Context, *GetUserNotificationSettingsRequest) (*GetUserNotificationSettingsResponse, error)
	UpdateUserNotificationSettings(context.Context, *UpdateUserNotificationSettingsRequest) (*UpdateUserNotificationSettingsResponse, error)
	CheckNotificationEnabled(context.Context, *CheckNotificationEnabledRequest) (*CheckNotificationEnabledResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) CreateNotificationTemplate(context.Context, *CreateNotificationTemplateRequest) (*CreateNotificationTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotificationTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotificationTemplate(context.Context, *GetNotificationTemplateRequest) (*GetNotificationTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotificationTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateNotificationTemplate(context.Context, *UpdateNotificationTemplateRequest) (*UpdateNotificationTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotificationTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteNotificationTemplate(context.Context, *DeleteNotificationTemplateRequest) (*DeleteNotificationTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNotificationTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) ListNotificationTemplates(context.Context, *ListNotificationTemplatesRequest) (*ListNotificationTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotificationTemplates not implemented")
}
func (UnimplementedNotificationServiceServer) GetTemplateByEvent(context.Context, *GetTemplateByEventRequest) (*GetTemplateByEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateByEvent not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNotification(context.Context, *CreateNotificationRequest) (*CreateNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotification not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotification not implemented")
}
func (UnimplementedNotificationServiceServer) ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotificationsByUser(context.Context, *GetNotificationsByUserRequest) (*GetNotificationsByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotificationsByUser not implemented")
}
func (UnimplementedNotificationServiceServer) MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*MarkNotificationReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedNotificationServiceServer) MarkAllNotificationsRead(context.Context, *MarkAllNotificationsReadRequest) (*MarkAllNotificationsReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAllNotificationsRead not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteNotification(context.Context, *DeleteNotificationRequest) (*DeleteNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNotification not implemented")
}
func (UnimplementedNotificationServiceServer) GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedNotificationServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedNotificationServiceServer) SendBulkNotification(context.Context, *SendBulkNotificationRequest) (*SendBulkNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBulkNotification not implemented")
}
func (UnimplementedNotificationServiceServer) SendMultiChannelNotification(context.Context, *SendMultiChannelNotificationRequest) (*SendMultiChannelNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMultiChannelNotification not implemented")
}
func (UnimplementedNotificationServiceServer) RegisterDeviceToken(context.Context, *RegisterDeviceTokenRequest) (*RegisterDeviceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDeviceToken not implemented")
}
func (UnimplementedNotificationServiceServer) UnregisterDeviceToken(context.Context, *UnregisterDeviceTokenRequest) (*UnregisterDeviceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterDeviceToken not implemented")
}
func (UnimplementedNotificationServiceServer) GetDeviceTokensByUser(context.Context, *GetDeviceTokensByUserRequest) (*GetDeviceTokensByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceTokensByUser not implemented")
}
func (UnimplementedNotificationServiceServer) DeactivateDeviceToken(context.Context, *DeactivateDeviceTokenRequest) (*DeactivateDeviceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateDeviceToken not implemented")
}
func (UnimplementedNotificationServiceServer) GetUserNotificationSettings(context.Context, *GetUserNotificationSettingsRequest) (*GetUserNotificationSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNotificationSettings not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateUserNotificationSettings(context.Context, *UpdateUserNotificationSettingsRequest) (*UpdateUserNotificationSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserNotificationSettings not implemented")
}
func (UnimplementedNotificationServiceServer) CheckNotificationEnabled(context.Context, *CheckNotificationEnabledRequest) (*CheckNotificationEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNotificationEnabled not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_CreateNotificationTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotificationTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotificationTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotificationTemplate(ctx, req.(*CreateNotificationTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotificationTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotificationTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotificationTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotificationTemplate(ctx, req.(*GetNotificationTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateNotificationTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateNotificationTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateNotificationTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateNotificationTemplate(ctx, req.(*UpdateNotificationTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteNotificationTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteNotificationTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteNotificationTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteNotificationTemplate(ctx, req.(*DeleteNotificationTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListNotificationTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotificationTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotificationTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotificationTemplates(ctx, req.(*ListNotificationTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetTemplateByEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateByEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetTemplateByEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetTemplateByEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetTemplateByEvent(ctx, req.(*GetTemplateByEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotification(ctx, req.(*CreateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotification(ctx, req.(*GetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotificationsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotificationsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotificationsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotificationsByUser(ctx, req.(*GetNotificationsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkNotificationRead(ctx, req.(*MarkNotificationReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkAllNotificationsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllNotificationsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkAllNotificationsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkAllNotificationsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkAllNotificationsRead(ctx, req.(*MarkAllNotificationsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteNotification(ctx, req.(*DeleteNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendBulkNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBulkNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendBulkNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendBulkNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendBulkNotification(ctx, req.(*SendBulkNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendMultiChannelNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMultiChannelNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendMultiChannelNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendMultiChannelNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendMultiChannelNotification(ctx, req.(*SendMultiChannelNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_RegisterDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).RegisterDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_RegisterDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).RegisterDeviceToken(ctx, req.(*RegisterDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UnregisterDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UnregisterDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UnregisterDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UnregisterDeviceToken(ctx, req.(*UnregisterDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetDeviceTokensByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceTokensByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetDeviceTokensByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetDeviceTokensByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetDeviceTokensByUser(ctx, req.(*GetDeviceTokensByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeactivateDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeactivateDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeactivateDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeactivateDeviceToken(ctx, req.(*DeactivateDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetUserNotificationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetUserNotificationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetUserNotificationSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetUserNotificationSettings(ctx, req.(*GetUserNotificationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateUserNotificationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserNotificationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateUserNotificationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateUserNotificationSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateUserNotificationSettings(ctx, req.(*UpdateUserNotificationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CheckNotificationEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNotificationEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CheckNotificationEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CheckNotificationEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CheckNotificationEnabled(ctx, req.(*CheckNotificationEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hirehub.notification.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotificationTemplate",
			Handler:    _NotificationService_CreateNotificationTemplate_Handler,
		},
		{
			MethodName: "GetNotificationTemplate",
			Handler:    _NotificationService_GetNotificationTemplate_Handler,
		},
		{
			MethodName: "UpdateNotificationTemplate",
			Handler:    _NotificationService_UpdateNotificationTemplate_Handler,
		},
		{
			MethodName: "DeleteNotificationTemplate",
			Handler:    _NotificationService_DeleteNotificationTemplate_Handler,
		},
		{
			MethodName: "ListNotificationTemplates",
			Handler:    _NotificationService_ListNotificationTemplates_Handler,
		},
		{
			MethodName: "GetTemplateByEvent",
			Handler:    _NotificationService_GetTemplateByEvent_Handler,
		},
		{
			MethodName: "CreateNotification",
			Handler:    _NotificationService_CreateNotification_Handler,
		},
		{
			MethodName: "GetNotification",
			Handler:    _NotificationService_GetNotification_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _NotificationService_ListNotifications_Handler,
		},
		{
			MethodName: "GetNotificationsByUser",
			Handler:    _NotificationService_GetNotificationsByUser_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _NotificationService_MarkNotificationRead_Handler,
		},
		{
			MethodName: "MarkAllNotificationsRead",
			Handler:    _NotificationService_MarkAllNotificationsRead_Handler,
		},
		{
			MethodName: "DeleteNotification",
			Handler:    _NotificationService_DeleteNotification_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _NotificationService_GetUnreadCount_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _NotificationService_SendNotification_Handler,
		},
		{
			MethodName: "SendBulkNotification",
			Handler:    _NotificationService_SendBulkNotification_Handler,
		},
		{
			MethodName: "SendMultiChannelNotification",
			Handler:    _NotificationService_SendMultiChannelNotification_Handler,
		},
		{
			MethodName: "RegisterDeviceToken",
			Handler:    _NotificationService_RegisterDeviceToken_Handler,
		},
		{
			MethodName: "UnregisterDeviceToken",
			Handler:    _NotificationService_UnregisterDeviceToken_Handler,
		},
		{
			MethodName: "GetDeviceTokensByUser",
			Handler:    _NotificationService_GetDeviceTokensByUser_Handler,
		},
		{
			MethodName: "DeactivateDeviceToken",
			Handler:    _NotificationService_DeactivateDeviceToken_Handler,
		},
		{
			MethodName: "GetUserNotificationSettings",
			Handler:    _NotificationService_GetUserNotificationSettings_Handler,
		},
		{
			MethodName: "UpdateUserNotificationSettings",
			Handler:    _NotificationService_UpdateUserNotificationSettings_Handler,
		},
		{
			MethodName: "CheckNotificationEnabled",
			Handler:    _NotificationService_CheckNotificationEnabled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/notification.proto",
}
