apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: clickhouse
    targetRevision: 6.2.16
    helm:
      releaseName: clickhouse
      values: |
        # Single shard, single replica for demo
        shards: 1
        replicaCount: 1

        # Resources
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi

        # Persistence
        persistence:
          enabled: true
          size: 10Gi

        # Authentication
        auth:
          username: admin
          password: clickhouse123

        # Keeper disabled for single node
        keeper:
          enabled: false

        # ZooKeeper disabled for single node
        zookeeper:
          enabled: false

  destination:
    name: in-cluster
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
