apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.8.0
    helm:
      releaseName: grafana
      values: |
        # Replicas
        replicas: 1

        # Resources
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

        # Persistence
        persistence:
          enabled: true
          size: 5Gi

        # Admin credentials
        adminUser: admin
        adminPassword: grafana123

        # Plugins for additional datasources
        plugins:
          - grafana-clickhouse-datasource
          - grafana-opensearch-datasource

        # Datasources configuration
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              # Loki - Log aggregation (LogQL)
              - name: Loki
                type: loki
                access: proxy
                url: http://loki-gateway.monitoring.svc.cluster.local:3100
                isDefault: false
                jsonData:
                  maxLines: 1000
                  derivedFields:
                    - datasourceUid: tempo
                      matcherRegex: "traceID=(\\w+)"
                      name: TraceID
                      url: "$${__value.raw}"

              # Tempo - Distributed tracing (TraceQL)
              - name: Tempo
                type: tempo
                uid: tempo
                access: proxy
                url: http://tempo-query-frontend.monitoring.svc.cluster.local:3100
                isDefault: false
                jsonData:
                  httpMethod: GET
                  tracesToLogs:
                    datasourceUid: loki
                    tags: ['k8s.namespace.name', 'k8s.pod.name']
                    mapTagNamesEnabled: true
                    mappedTags:
                      - key: k8s.namespace.name
                        value: namespace
                      - key: k8s.pod.name
                        value: pod
                  serviceMap:
                    datasourceUid: mimir
                  nodeGraph:
                    enabled: true
                  lokiSearch:
                    datasourceUid: loki

              # Mimir - Long-term metrics (PromQL)
              - name: Mimir
                type: prometheus
                uid: mimir
                access: proxy
                url: http://mimir-nginx.monitoring.svc.cluster.local:80/prometheus
                isDefault: true
                jsonData:
                  httpMethod: POST
                  prometheusType: Mimir

              # ClickHouse - SQL log analytics
              - name: ClickHouse
                type: grafana-clickhouse-datasource
                access: proxy
                url: clickhouse.monitoring.svc.cluster.local:9000
                isDefault: false
                jsonData:
                  host: clickhouse.monitoring.svc.cluster.local
                  port: 9000
                  protocol: native
                  username: admin
                  defaultDatabase: otel
                secureJsonData:
                  password: clickhouse123

              # OpenSearch - Full-text search (Placeholder - update endpoint after Terraform)
              - name: OpenSearch
                type: grafana-opensearch-datasource
                access: proxy
                url: https://opensearch.placeholder.local
                isDefault: false
                jsonData:
                  database: logs
                  flavor: opensearch
                  version: "2.11.0"
                  timeField: "@timestamp"
                  logMessageField: message
                  logLevelField: level

        # Dashboards provisioning
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'default'
                orgId: 1
                folder: 'LGTM'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default

        # Pre-configured dashboards
        dashboards:
          default:
            # Kubernetes overview
            kubernetes-overview:
              gnetId: 15520
              revision: 1
              datasource: Mimir

            # Loki logs dashboard
            loki-logs:
              gnetId: 13639
              revision: 2
              datasource: Loki

            # OTEL Collector
            otel-collector:
              gnetId: 15983
              revision: 1
              datasource: Mimir

        # Grafana configuration
        grafana.ini:
          server:
            # CloudFront proxy support
            root_url: "%(protocol)s://%(domain)s/"
            serve_from_sub_path: false
          security:
            # Allow embedding in iframes (if needed)
            allow_embedding: true
            # Cookie settings for CloudFront
            cookie_secure: true
            cookie_samesite: none
          analytics:
            check_for_updates: false
          log:
            mode: console
          grafana_net:
            url: https://grafana.net
          # Live/WebSocket configuration
          live:
            allowed_origins: "*"
          # Feature toggles for new features
          feature_toggles:
            enable: traceqlEditor tempoSearch tempoBackendSearch tempoApmTable

        # Service configuration - NLB for CloudFront origin
        service:
          type: LoadBalancer
          port: 80
          targetPort: 3000
          annotations:
            # AWS Load Balancer Controller - NLB
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            # Security Group - CloudFront only
            service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0ab9a81a0cbe68369
            # Health check
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /api/health
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
            # Cross-zone load balancing
            service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true

        # Ingress (disabled - using NLB + CloudFront)
        ingress:
          enabled: false

  destination:
    name: in-cluster
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
