---
# Simplified Monitoring Stack ArgoCD Application
# Deploys: Loki, Tempo, Mimir, ClickHouse, Grafana, OTEL Collector
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/awskrug/hirehub-demo.git
    path: infrastructure/k8s/monitoring
    targetRevision: main
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
