apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: 1.24.0
    helm:
      releaseName: tempo
      values: |
        # MinIO disabled - using Loki's MinIO
        minio:
          enabled: false

        # Storage configuration - using Loki's MinIO
        storage:
          trace:
            backend: s3
            s3:
              bucket: tempo-traces
              endpoint: loki-minio.monitoring.svc.cluster.local:9000
              access_key: enterprise-logs
              secret_key: supersecret
              insecure: true

        # Distributor - receives traces
        distributor:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        # Ingester - writes to storage
        ingester:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          persistence:
            enabled: true
            size: 10Gi

        # Querier - reads traces
        querier:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        # Query Frontend
        queryFrontend:
          replicas: 1
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi

        # Compactor
        compactor:
          replicas: 1
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi

        # Metrics generator (optional - generates metrics from traces)
        metricsGenerator:
          enabled: true
          replicas: 1
          config:
            storage:
              remote_write:
                - url: http://mimir-distributor.monitoring.svc.cluster.local:8080/api/v1/push

        # Gateway
        gateway:
          enabled: true
          replicas: 1

        # Traces configuration
        traces:
          otlp:
            http:
              enabled: true
            grpc:
              enabled: true
          zipkin:
            enabled: false
          jaeger:
            thriftHttp:
              enabled: false

  destination:
    name: in-cluster
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
