// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: job/v1/job.proto

package jobv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobService_CreateJob_FullMethodName              = "/hirehub.job.v1.JobService/CreateJob"
	JobService_GetJob_FullMethodName                 = "/hirehub.job.v1.JobService/GetJob"
	JobService_UpdateJob_FullMethodName              = "/hirehub.job.v1.JobService/UpdateJob"
	JobService_DeleteJob_FullMethodName              = "/hirehub.job.v1.JobService/DeleteJob"
	JobService_ListJobs_FullMethodName               = "/hirehub.job.v1.JobService/ListJobs"
	JobService_SearchJobs_FullMethodName             = "/hirehub.job.v1.JobService/SearchJobs"
	JobService_GetJobsByCompany_FullMethodName       = "/hirehub.job.v1.JobService/GetJobsByCompany"
	JobService_IncrementJobViewCount_FullMethodName  = "/hirehub.job.v1.JobService/IncrementJobViewCount"
	JobService_IncrementJobApplyCount_FullMethodName = "/hirehub.job.v1.JobService/IncrementJobApplyCount"
	JobService_CreateSkillTag_FullMethodName         = "/hirehub.job.v1.JobService/CreateSkillTag"
	JobService_GetSkillTag_FullMethodName            = "/hirehub.job.v1.JobService/GetSkillTag"
	JobService_UpdateSkillTag_FullMethodName         = "/hirehub.job.v1.JobService/UpdateSkillTag"
	JobService_DeleteSkillTag_FullMethodName         = "/hirehub.job.v1.JobService/DeleteSkillTag"
	JobService_ListSkillTags_FullMethodName          = "/hirehub.job.v1.JobService/ListSkillTags"
	JobService_SearchSkillTags_FullMethodName        = "/hirehub.job.v1.JobService/SearchSkillTags"
	JobService_BatchCreateSkillTags_FullMethodName   = "/hirehub.job.v1.JobService/BatchCreateSkillTags"
)

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobServiceClient interface {
	// Job CRUD
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*UpdateJobResponse, error)
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	SearchJobs(ctx context.Context, in *SearchJobsRequest, opts ...grpc.CallOption) (*SearchJobsResponse, error)
	GetJobsByCompany(ctx context.Context, in *GetJobsByCompanyRequest, opts ...grpc.CallOption) (*GetJobsByCompanyResponse, error)
	// Job counters
	IncrementJobViewCount(ctx context.Context, in *IncrementJobViewCountRequest, opts ...grpc.CallOption) (*IncrementJobViewCountResponse, error)
	IncrementJobApplyCount(ctx context.Context, in *IncrementJobApplyCountRequest, opts ...grpc.CallOption) (*IncrementJobApplyCountResponse, error)
	// SkillTag CRUD
	CreateSkillTag(ctx context.Context, in *CreateSkillTagRequest, opts ...grpc.CallOption) (*CreateSkillTagResponse, error)
	GetSkillTag(ctx context.Context, in *GetSkillTagRequest, opts ...grpc.CallOption) (*GetSkillTagResponse, error)
	UpdateSkillTag(ctx context.Context, in *UpdateSkillTagRequest, opts ...grpc.CallOption) (*UpdateSkillTagResponse, error)
	DeleteSkillTag(ctx context.Context, in *DeleteSkillTagRequest, opts ...grpc.CallOption) (*DeleteSkillTagResponse, error)
	ListSkillTags(ctx context.Context, in *ListSkillTagsRequest, opts ...grpc.CallOption) (*ListSkillTagsResponse, error)
	SearchSkillTags(ctx context.Context, in *SearchSkillTagsRequest, opts ...grpc.CallOption) (*SearchSkillTagsResponse, error)
	BatchCreateSkillTags(ctx context.Context, in *BatchCreateSkillTagsRequest, opts ...grpc.CallOption) (*BatchCreateSkillTagsResponse, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, JobService_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, JobService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*UpdateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobResponse)
	err := c.cc.Invoke(ctx, JobService_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobResponse)
	err := c.cc.Invoke(ctx, JobService_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, JobService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) SearchJobs(ctx context.Context, in *SearchJobsRequest, opts ...grpc.CallOption) (*SearchJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchJobsResponse)
	err := c.cc.Invoke(ctx, JobService_SearchJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJobsByCompany(ctx context.Context, in *GetJobsByCompanyRequest, opts ...grpc.CallOption) (*GetJobsByCompanyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobsByCompanyResponse)
	err := c.cc.Invoke(ctx, JobService_GetJobsByCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) IncrementJobViewCount(ctx context.Context, in *IncrementJobViewCountRequest, opts ...grpc.CallOption) (*IncrementJobViewCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementJobViewCountResponse)
	err := c.cc.Invoke(ctx, JobService_IncrementJobViewCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) IncrementJobApplyCount(ctx context.Context, in *IncrementJobApplyCountRequest, opts ...grpc.CallOption) (*IncrementJobApplyCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementJobApplyCountResponse)
	err := c.cc.Invoke(ctx, JobService_IncrementJobApplyCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CreateSkillTag(ctx context.Context, in *CreateSkillTagRequest, opts ...grpc.CallOption) (*CreateSkillTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSkillTagResponse)
	err := c.cc.Invoke(ctx, JobService_CreateSkillTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetSkillTag(ctx context.Context, in *GetSkillTagRequest, opts ...grpc.CallOption) (*GetSkillTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillTagResponse)
	err := c.cc.Invoke(ctx, JobService_GetSkillTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UpdateSkillTag(ctx context.Context, in *UpdateSkillTagRequest, opts ...grpc.CallOption) (*UpdateSkillTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSkillTagResponse)
	err := c.cc.Invoke(ctx, JobService_UpdateSkillTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) DeleteSkillTag(ctx context.Context, in *DeleteSkillTagRequest, opts ...grpc.CallOption) (*DeleteSkillTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSkillTagResponse)
	err := c.cc.Invoke(ctx, JobService_DeleteSkillTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ListSkillTags(ctx context.Context, in *ListSkillTagsRequest, opts ...grpc.CallOption) (*ListSkillTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillTagsResponse)
	err := c.cc.Invoke(ctx, JobService_ListSkillTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) SearchSkillTags(ctx context.Context, in *SearchSkillTagsRequest, opts ...grpc.CallOption) (*SearchSkillTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSkillTagsResponse)
	err := c.cc.Invoke(ctx, JobService_SearchSkillTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) BatchCreateSkillTags(ctx context.Context, in *BatchCreateSkillTagsRequest, opts ...grpc.CallOption) (*BatchCreateSkillTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateSkillTagsResponse)
	err := c.cc.Invoke(ctx, JobService_BatchCreateSkillTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
// All implementations must embed UnimplementedJobServiceServer
// for forward compatibility.
type JobServiceServer interface {
	// Job CRUD
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	UpdateJob(context.Context, *UpdateJobRequest) (*UpdateJobResponse, error)
	DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	SearchJobs(context.Context, *SearchJobsRequest) (*SearchJobsResponse, error)
	GetJobsByCompany(context.Context, *GetJobsByCompanyRequest) (*GetJobsByCompanyResponse, error)
	// Job counters
	IncrementJobViewCount(context.Context, *IncrementJobViewCountRequest) (*IncrementJobViewCountResponse, error)
	IncrementJobApplyCount(context.Context, *IncrementJobApplyCountRequest) (*IncrementJobApplyCountResponse, error)
	// SkillTag CRUD
	CreateSkillTag(context.Context, *CreateSkillTagRequest) (*CreateSkillTagResponse, error)
	GetSkillTag(context.Context, *GetSkillTagRequest) (*GetSkillTagResponse, error)
	UpdateSkillTag(context.Context, *UpdateSkillTagRequest) (*UpdateSkillTagResponse, error)
	DeleteSkillTag(context.Context, *DeleteSkillTagRequest) (*DeleteSkillTagResponse, error)
	ListSkillTags(context.Context, *ListSkillTagsRequest) (*ListSkillTagsResponse, error)
	SearchSkillTags(context.Context, *SearchSkillTagsRequest) (*SearchSkillTagsResponse, error)
	BatchCreateSkillTags(context.Context, *BatchCreateSkillTagsRequest) (*BatchCreateSkillTagsResponse, error)
	mustEmbedUnimplementedJobServiceServer()
}

// UnimplementedJobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobServiceServer struct{}

func (UnimplementedJobServiceServer) CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedJobServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobServiceServer) UpdateJob(context.Context, *UpdateJobRequest) (*UpdateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedJobServiceServer) DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedJobServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedJobServiceServer) SearchJobs(context.Context, *SearchJobsRequest) (*SearchJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchJobs not implemented")
}
func (UnimplementedJobServiceServer) GetJobsByCompany(context.Context, *GetJobsByCompanyRequest) (*GetJobsByCompanyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobsByCompany not implemented")
}
func (UnimplementedJobServiceServer) IncrementJobViewCount(context.Context, *IncrementJobViewCountRequest) (*IncrementJobViewCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementJobViewCount not implemented")
}
func (UnimplementedJobServiceServer) IncrementJobApplyCount(context.Context, *IncrementJobApplyCountRequest) (*IncrementJobApplyCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementJobApplyCount not implemented")
}
func (UnimplementedJobServiceServer) CreateSkillTag(context.Context, *CreateSkillTagRequest) (*CreateSkillTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSkillTag not implemented")
}
func (UnimplementedJobServiceServer) GetSkillTag(context.Context, *GetSkillTagRequest) (*GetSkillTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillTag not implemented")
}
func (UnimplementedJobServiceServer) UpdateSkillTag(context.Context, *UpdateSkillTagRequest) (*UpdateSkillTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSkillTag not implemented")
}
func (UnimplementedJobServiceServer) DeleteSkillTag(context.Context, *DeleteSkillTagRequest) (*DeleteSkillTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkillTag not implemented")
}
func (UnimplementedJobServiceServer) ListSkillTags(context.Context, *ListSkillTagsRequest) (*ListSkillTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkillTags not implemented")
}
func (UnimplementedJobServiceServer) SearchSkillTags(context.Context, *SearchSkillTagsRequest) (*SearchSkillTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSkillTags not implemented")
}
func (UnimplementedJobServiceServer) BatchCreateSkillTags(context.Context, *BatchCreateSkillTagsRequest) (*BatchCreateSkillTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateSkillTags not implemented")
}
func (UnimplementedJobServiceServer) mustEmbedUnimplementedJobServiceServer() {}
func (UnimplementedJobServiceServer) testEmbeddedByValue()                    {}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	// If the following call panics, it indicates UnimplementedJobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).UpdateJob(ctx, req.(*UpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).DeleteJob(ctx, req.(*DeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_SearchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).SearchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_SearchJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).SearchJobs(ctx, req.(*SearchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJobsByCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsByCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJobsByCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetJobsByCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJobsByCompany(ctx, req.(*GetJobsByCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_IncrementJobViewCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementJobViewCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).IncrementJobViewCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_IncrementJobViewCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).IncrementJobViewCount(ctx, req.(*IncrementJobViewCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_IncrementJobApplyCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementJobApplyCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).IncrementJobApplyCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_IncrementJobApplyCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).IncrementJobApplyCount(ctx, req.(*IncrementJobApplyCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CreateSkillTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateSkillTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_CreateSkillTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateSkillTag(ctx, req.(*CreateSkillTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetSkillTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetSkillTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetSkillTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetSkillTag(ctx, req.(*GetSkillTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UpdateSkillTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkillTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).UpdateSkillTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_UpdateSkillTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).UpdateSkillTag(ctx, req.(*UpdateSkillTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_DeleteSkillTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).DeleteSkillTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_DeleteSkillTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).DeleteSkillTag(ctx, req.(*DeleteSkillTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ListSkillTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ListSkillTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_ListSkillTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ListSkillTags(ctx, req.(*ListSkillTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_SearchSkillTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSkillTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).SearchSkillTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_SearchSkillTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).SearchSkillTags(ctx, req.(*SearchSkillTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_BatchCreateSkillTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateSkillTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).BatchCreateSkillTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_BatchCreateSkillTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).BatchCreateSkillTags(ctx, req.(*BatchCreateSkillTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hirehub.job.v1.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobService_GetJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _JobService_UpdateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _JobService_DeleteJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _JobService_ListJobs_Handler,
		},
		{
			MethodName: "SearchJobs",
			Handler:    _JobService_SearchJobs_Handler,
		},
		{
			MethodName: "GetJobsByCompany",
			Handler:    _JobService_GetJobsByCompany_Handler,
		},
		{
			MethodName: "IncrementJobViewCount",
			Handler:    _JobService_IncrementJobViewCount_Handler,
		},
		{
			MethodName: "IncrementJobApplyCount",
			Handler:    _JobService_IncrementJobApplyCount_Handler,
		},
		{
			MethodName: "CreateSkillTag",
			Handler:    _JobService_CreateSkillTag_Handler,
		},
		{
			MethodName: "GetSkillTag",
			Handler:    _JobService_GetSkillTag_Handler,
		},
		{
			MethodName: "UpdateSkillTag",
			Handler:    _JobService_UpdateSkillTag_Handler,
		},
		{
			MethodName: "DeleteSkillTag",
			Handler:    _JobService_DeleteSkillTag_Handler,
		},
		{
			MethodName: "ListSkillTags",
			Handler:    _JobService_ListSkillTags_Handler,
		},
		{
			MethodName: "SearchSkillTags",
			Handler:    _JobService_SearchSkillTags_Handler,
		},
		{
			MethodName: "BatchCreateSkillTags",
			Handler:    _JobService_BatchCreateSkillTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job/v1/job.proto",
}
